blank_issues_enabled: true
contact_links:
  - name: Q&A
    url: https://github.com/NOAA-EMC/WW3/discussions/categories/q-a
    about: Ask the community for help
  - name: General
    url: https://github.com/NOAA-EMC/WW3/discussions/categories/general
    about: Chat about anything and everything here
